from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class JobStore(Protocol):
    def status_path(self, run_id: str) -> Path: ...

    def lineage_path(self, run_id: str) -> Path: ...

    def metrics_path(self, run_id: str) -> Path: ...

    def write_status(self, run_id: str, payload: dict[str, Any]) -> Path: ...

    def append_lineage_row(self, run_id: str, payload: dict[str, Any]) -> Path: ...

    def write_metrics(self, run_id: str, payload: dict[str, Any]) -> Path: ...

    def read_status(self, run_id: str) -> dict[str, Any] | None: ...

    def read_lineage(self, run_id: str, limit: int) -> list[dict[str, Any]] | None: ...

    def read_metrics(self, run_id: str) -> dict[str, Any] | None: ...
